# Пример использования класса framework.Dataloader

## Импорт библиотеки

In [1]:
import sys
sys.path.append("/Users/cube/Documents/Development/MAI/Сошников")
from framework.DataLoader import DataLoader

## Загрузка датасетов

### Iris Dataset

In [10]:
dl = DataLoader("iris")
dl.head()

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([0, 0, 0]))

In [12]:
dl.labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
dl.get_stats()

{'data_shape': (150, 4),
 'labels_shape': (150,),
 'data_type': dtype('float64'),
 'labels_type': dtype('int64'),
 'unique_labels': array([0, 1, 2]),
 'data_mean': np.float64(3.4644999999999997),
 'data_std': np.float64(1.9738430577598278)}

### MNIST


In [ ]:
dl = DataLoader("mnist")

### Diabets

In [ ]:
dl = DataLoader("diabetes")

### Wine


In [ ]:
dl = DataLoader("wine")